In [1]:
import numpy as np

# numpy array function

In [2]:
ls_1 = [1,2,3,4]

In [3]:
array_1 = np.array(ls_1)

In [4]:
print(ls_1)

[1, 2, 3, 4]


In [5]:
print (array_1)

[1 2 3 4]


In [6]:
ls_2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [7]:
array_2 = np.array (ls_2)

In [8]:
print (ls_2)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [9]:
print (array_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# numpy arange function

In [10]:
#تطبع ارقام بتسلسل معين

In [11]:
arange_1 = np.arange(1,15)

In [12]:
print (arange_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
arange_2 = np.arange(1,15,3)

In [14]:
print (arange_2)

[ 1  4  7 10 13]


# numpy zeros function

In [15]:
zeros_1 = np.zeros(9)

In [16]:
print (zeros_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
zeros_2 = np.zeros((3,3))

In [18]:
print (zeros_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# numpy ones function

In [19]:
ones_1 = np.ones (7)

In [20]:
print (ones_1)

[1. 1. 1. 1. 1. 1. 1.]


In [21]:
ones_2 = np.ones ((4,3))

In [22]:
print (ones_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# rand method

In [23]:
#  بتدينا قيم عشوائية بين0:1 

In [24]:
rand_1 = np.random.rand(3)

In [25]:
print(rand_1)

[0.60934145 0.25295926 0.06667102]


In [26]:
rand = np.random.rand(3)

In [27]:
#  بتدينا قيم عشوائية بين0:1 في شكل مصفوفة

In [28]:
randint_1 = np.random.rand(4,2)

In [29]:
print (randint_1)

[[0.50738939 0.79547215]
 [0.42150678 0.79864822]
 [0.83859348 0.75713618]
 [0.25049297 0.13051536]]


In [30]:
randint_1.dtype

dtype('float64')

# randint method

In [31]:
# بتدينا قيم عشوائية صحيحة

In [32]:
randint_1 = np.random.randint(50)

In [33]:
print (randint_1)

41


In [34]:
randint_2 = np.random.randint(50,100)

In [35]:
print (randint_2)

96


In [36]:
randint_3 = np.random.randint(50,100,10)

In [37]:
print (randint_3)

[68 81 60 76 52 84 68 55 61 88]


In [38]:
randint_4 = np.random.randint(50,100,(4,3))

In [39]:
print (randint_4)

[[50 61 63]
 [98 57 60]
 [77 92 94]
 [76 53 71]]


# reshape method

In [40]:
shape = randint_3.reshape(2,5)

In [41]:
print (shape)

[[68 81 60 76 52]
 [84 68 55 61 88]]


# shuffle method

In [42]:
np.random.shuffle(arange_1)

In [43]:
arange_1

array([ 6,  7, 12, 11,  2,  9,  5, 14, 10,  1,  8, 13,  4,  3])

In [44]:
np.random.shuffle(shape)

In [45]:
print (shape)

[[84 68 55 61 88]
 [68 81 60 76 52]]


# maximum & minimum method

In [46]:
maximum = randint_4.max()

In [47]:
print ("maximum : " + str (maximum))

maximum : 98


In [48]:
minimum = randint_4.min()

In [49]:
print ("minimum : " + str (minimum))

minimum : 50


# argmax & argmin method

In [50]:
max_index = randint_4.argmax()

In [51]:
print (max_index)

3


In [52]:
min_index = randint_4.argmin()

In [53]:
print (min_index)

0


# shape method

In [54]:
shape = randint_4.shape

In [55]:
print (shape)

(4, 3)


In [56]:
print (shape[0])

4


In [57]:
print (shape[1])

3


# numpy ceil function

In [58]:
#تقوم بتقريب الرقم العشري لاقرب رقم صحيح اكبر منه

In [59]:
ceil = np.ceil(3.7)

In [60]:
print (ceil)

4.0


# numpy floor function

In [61]:
floor = np.floor(2.99999)

In [62]:
print (floor)

2.0


# numpy round function

In [63]:
r_1 = np.round (4.2)

In [64]:
print (r_1)

4.0


In [65]:
r_2 = np.round (4.7)

In [66]:
print (r_2)

5.0


# numpy add function

In [67]:
add_1 = np.add (3,5)

In [68]:
print (add_1)

8


In [69]:
add_2 = np.add (randint_4,2)

In [70]:
print (add_2)

[[ 52  63  65]
 [100  59  62]
 [ 79  94  96]
 [ 78  55  73]]


In [71]:
add_3 = np.add (randint_4,add_2)

In [72]:
print (add_3)

[[102 124 128]
 [198 116 122]
 [156 186 190]
 [154 108 144]]


# numpy multiply function

In [73]:
mul_1 = np.multiply (3,2)

In [74]:
print (mul_1)

6


In [75]:
mul_2 = np.multiply (randint_4,2)

In [76]:
print (mul_2)

[[100 122 126]
 [196 114 120]
 [154 184 188]
 [152 106 142]]


# numpy divide function

In [77]:
div_1 = np.divide (10,2)

In [78]:
print (div_1)

5.0


In [79]:
div_2 = np.divide (randint_4,2)

In [80]:
print(div_2)

[[25.  30.5 31.5]
 [49.  28.5 30. ]
 [38.5 46.  47. ]
 [38.  26.5 35.5]]


In [81]:
div_3 = np.divide (randint_4,div_2)

In [82]:
print (div_3)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# sum method

In [83]:
sum_ = div_2.sum()

In [84]:
sum_

426.0